Repository SYSONE-PICKME/PICKME, pull requests merged in 2024-09, with the labels that each got.

#2 [FEAT]: 초기 도메인 코드 구현
  pickme/src/main/java/project/pickme/bid/domain/Bid.java
  pickme/src/main/java/project/pickme/charge/domain/Charge.java
  pickme/src/main/java/project/pickme/customs/domain/Customs.java
  pickme/src/main/java/project/pickme/delivery/constant/DeliveryType.java
  pickme/src/main/java/project/pickme/delivery/doamin/Delivery.java
  pickme/src/main/java/project/pickme/image/domain/Image.java
  pickme/src/main/java/project/pickme/item/constant/Status.java
  pickme/src/main/java/project/pickme/item/domain/Category.java
  pickme/src/main/java/project/pickme/item/domain/Item.java
  pickme/src/main/java/project/pickme/item/domain/ItemLaw.java
  pickme/src/main/java/project/pickme/item/domain/Law.java
  pickme/src/main/java/project/pickme/like/domain/Like.java
  pickme/src/main/java/project/pickme/notice/domain/Notice.java
  pickme/src/main/java/project/pickme/payment/domain/Payment.java
  pickme/src/main/java/project/pickme/unit/domain/Unit.java
  pickme/src/main/java/project/pickme/user/constant/Type.java
  pickme/src/main/java/project/pickme/user/domain/User.java
  pickme/src/main/resources/static/index.html
  pickme/src/main/resources/templates/index.html
Labels: FEAT, BE

#7 [DOCS]: 환경설정 추가, yml파일 gitignore 설정
  pickme/.gitignore
  pickme/src/main/resources/application.properties
Labels: BE, DOCS

#17 [FEAT]: 회원가입 기능 + 회원가입 화면 구현
  pickme/build.gradle
  pickme/src/main/java/project/pickme/PickmeApplication.java
  pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
  pickme/src/main/java/project/pickme/user/constant/Role.java
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/java/project/pickme/user/domain/User.java
  pickme/src/main/java/project/pickme/user/dto/SignUpDto.java
  pickme/src/main/java/project/pickme/user/repository/UserMapper.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/mapper/UserMapper.xml
  pickme/src/main/resources/static/user/css/signUp.css
  pickme/src/main/resources/static/user/js/signUp.js
  pickme/src/main/resources/templates/index.html
  pickme/src/main/resources/templates/user/loginForm.html
  pickme/src/main/resources/templates/user/signUpForm.html
  pickme/src/test/java/project/pickme/user/controller/UserControllerTest.java
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FEAT, BE, FE, TEST

#9 [FEAT]: header, footer, layout 추가
  pickme/build.gradle
  pickme/src/main/java/project/pickme/PickmeApplication.java
  pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
  pickme/src/main/java/project/pickme/user/constant/Role.java
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/java/project/pickme/user/domain/User.java
  pickme/src/main/java/project/pickme/user/dto/SignUpDto.java
  pickme/src/main/java/project/pickme/user/repository/UserMapper.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/mapper/UserMapper.xml
  pickme/src/main/resources/static/css/footer.css
  pickme/src/main/resources/static/css/header.css
  pickme/src/main/resources/static/css/index.css
  pickme/src/main/resources/static/images/github_pixel_logo.png
  pickme/src/main/resources/static/index.html
  pickme/src/main/resources/static/user/css/signUp.css
  pickme/src/main/resources/static/user/js/signUp.js
  pickme/src/main/resources/templates/fragments/footer.html
  pickme/src/main/resources/templates/fragments/header.html
  pickme/src/main/resources/templates/index.html
  pickme/src/main/resources/templates/layouts/layout.html
  pickme/src/main/resources/templates/user/signUpForm.html
  pickme/src/test/java/project/pickme/user/controller/UserControllerTest.java
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FEAT, FE

#21 [FEAT]: 포인트 충전 기능 구현
  pickme/build.gradle
  pickme/src/main/java/project/pickme/charge/config/IamportConfig.java
  pickme/src/main/java/project/pickme/charge/controller/ChargeController.java
  pickme/src/main/java/project/pickme/charge/controller/ChargeRestController.java
  pickme/src/main/java/project/pickme/charge/dto/ChargeDto.java
  pickme/src/main/java/project/pickme/charge/mapper/ChargeMapper.java
  pickme/src/main/java/project/pickme/charge/service/ChargeService.java
  pickme/src/main/resources/mapper/ChargeMapper.xml
  pickme/src/main/resources/static/charge/style.css
  pickme/src/main/resources/templates/charge/charge.html
Labels: FEAT, BE, FE, STYLE

#23 [FEAT]: 메인 화면 정적 구현
  pickme/src/main/resources/static/css/userMain.css
  pickme/src/main/resources/static/images/administrative-fine.png
  pickme/src/main/resources/static/images/annoucement.png
  pickme/src/main/resources/static/images/auction.png
  pickme/src/main/resources/static/images/data-analysis.png
  pickme/src/main/resources/static/images/imsi.png
  pickme/src/main/resources/static/images/laptop.png
  pickme/src/main/resources/static/images/law.png
  pickme/src/main/resources/static/images/myPage.png
  pickme/src/main/resources/static/images/notice.png
  pickme/src/main/resources/static/images/planning.jpg
  pickme/src/main/resources/static/images/point.png
  pickme/src/main/resources/static/images/search-engine.png
  pickme/src/main/resources/static/index.html
  pickme/src/main/resources/static/js/userMain.js
  pickme/src/main/resources/templates/index.html
Labels: FEAT, FE

#26 [FEAT]: 포인트 충전 기능과 유저 기능 연결
  pickme/src/main/java/project/pickme/charge/controller/ChargeController.java
  pickme/src/main/java/project/pickme/charge/controller/ChargeRestController.java
  pickme/src/main/java/project/pickme/charge/dto/ChargeRequest.java
  pickme/src/main/java/project/pickme/charge/service/ChargeService.java
  pickme/src/main/java/project/pickme/user/dto/UserDto.java
  pickme/src/main/java/project/pickme/user/repository/UserMapper.java
  pickme/src/main/resources/mapper/UserMapper.xml
  pickme/src/main/resources/templates/charge/charge.html
Labels: BE, FE

#34 [FEAT]: 공매품 단순 조회 기능 구현
  pickme/src/main/java/project/pickme/item/FindItemService.java
  pickme/src/main/java/project/pickme/item/controller/FindItemController.java
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/java/project/pickme/item/mapper/FindItemMapper.java
  pickme/src/main/java/project/pickme/user/constant/Type.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/item/css/style.css
  pickme/src/main/resources/static/item/js/countdown.js
  pickme/src/main/resources/static/item/js/image.js
  pickme/src/main/resources/templates/item/item.html
Labels: FEAT, BE, FE

#40 [FEAT]: 실시간 공매 입찰 그래프 구현
  pickme/src/main/java/project/pickme/bid/dto/AddBidDto.java
  pickme/src/main/java/project/pickme/bid/dto/OneBidItemDto.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/java/project/pickme/common/auth/CustomAuthenticationSuccessHandler.java
  pickme/src/main/java/project/pickme/user/dto/SignUpDto.java
  pickme/src/main/java/project/pickme/user/service/CustomsService.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/static/css/bid/bidPage.css
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/main/resources/static/js/bid/chart.js
  pickme/src/main/resources/templates/bid/bidPage.html
  pickme/src/test/java/project/pickme/bid/repository/BidMapperTest.java
Labels: FEAT, BE, FE, TEST

#41 [FEAT]: 공매품 리스트 조회 & 필터링 기능 구현
  pickme/src/main/java/project/pickme/charge/controller/ChargeController.java
  pickme/src/main/java/project/pickme/charge/repository/ChargeMapper.java
  pickme/src/main/java/project/pickme/charge/service/ChargeService.java
  pickme/src/main/java/project/pickme/item/FindItemService.java
  pickme/src/main/java/project/pickme/item/controller/FindItemController.java
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/resources/mapper/ChargeMapper.xml
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/images/battery.png
  pickme/src/main/resources/static/images/clothes.png
  pickme/src/main/resources/static/images/fridge.png
  pickme/src/main/resources/static/images/furniture.png
  pickme/src/main/resources/static/images/tableware.png
  pickme/src/main/resources/static/item/css/list.css
  pickme/src/main/resources/static/item/js/filtering.js
  pickme/src/main/resources/templates/item/list.html
Labels: FEAT, BE, FE

#42 [FEAT]: 공매품 등록 기능 구현
  pickme/build.gradle
  pickme/src/main/java/project/pickme/config/S3Config.java
  pickme/src/main/java/project/pickme/item/constant/Category.java
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
  pickme/src/main/java/project/pickme/item/domain/Category.java
  pickme/src/main/java/project/pickme/item/dto/ImageDto.java
  pickme/src/main/java/project/pickme/item/dto/ItemDto.java
  pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
  pickme/src/main/java/project/pickme/item/dto/ItemLawDto.java
  pickme/src/main/java/project/pickme/item/dto/LawDto.java
  pickme/src/main/java/project/pickme/item/repository/ImageMapper.java
  pickme/src/main/java/project/pickme/item/repository/ItemLawMapper.java
  pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
  pickme/src/main/java/project/pickme/item/repository/LawMapper.java
  pickme/src/main/java/project/pickme/item/service/ItemService.java
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/mapper/ImageMapper.xml
  pickme/src/main/resources/mapper/ItemLawMapper.xml
  pickme/src/main/resources/mapper/ItemMapper.xml
  pickme/src/main/resources/mapper/LawMapper.xml
  pickme/src/main/resources/static/css/item/item.css
  pickme/src/main/resources/static/js/item/item.js
  pickme/src/main/resources/templates/index.html
  pickme/src/main/resources/templates/item/create-item.html
Labels: FIX, FEAT, BE, REFACTOR, FE, STYLE

#50 [FEAT]: 단일 아이템 내꺼야 기능 구현
  pickme/src/main/java/project/pickme/item/FindItemService.java
  pickme/src/main/java/project/pickme/item/controller/FindItemController.java
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/java/project/pickme/like/controller/LikeRestController.java
  pickme/src/main/java/project/pickme/like/dto/LikeDto.java
  pickme/src/main/java/project/pickme/like/repository/LikeMapper.java
  pickme/src/main/java/project/pickme/like/service/LikeService.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/mapper/LikeMapper.xml
  pickme/src/main/resources/static/item/css/style.css
  pickme/src/main/resources/static/item/js/like.js
  pickme/src/main/resources/templates/item/item.html
Labels: FEAT, BE, FE

#47 [FEAT]: 내 낙찰 목록 조회(배송 현황 조회)
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/bid/dto/SuccessfulBidDto.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/static/css/bid/success.css
  pickme/src/main/resources/templates/bid/successfulBidList.html
Labels: FEAT, BE, FE, STYLE

#53 [FEAT]: 등록한 공매 물품 조회
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
  pickme/src/main/java/project/pickme/item/dto/ImageDto.java
  pickme/src/main/java/project/pickme/item/dto/ItemDto.java
  pickme/src/main/java/project/pickme/item/dto/LawDto.java
  pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
  pickme/src/main/java/project/pickme/item/service/ItemService.java
  pickme/src/main/resources/mapper/ItemMapper.xml
  pickme/src/main/resources/static/css/bid/success.css
  pickme/src/main/resources/templates/item/createItem.html
  pickme/src/main/resources/templates/item/customsItemList.html
Labels: FEAT, BE, FE, STYLE

#58 [REFACTOR]: issue36번 리뷰사항 수정
  pickme/src/main/java/project/pickme/common/exception/ErrorCode.java
  pickme/src/main/java/project/pickme/item/service/ItemService.java
  pickme/src/main/java/project/pickme/s3/config/S3Config.java
  pickme/src/main/java/project/pickme/s3/service/S3Service.java
Labels: FIX, REFACTOR

#56 [FEAT]: 입찰 성공 여부 + 메일 전송 기능 구현
  pickme/build.gradle
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/bid/domain/Bid.java
  pickme/src/main/java/project/pickme/bid/dto/AddBidDto.java
  pickme/src/main/java/project/pickme/bid/dto/SelectedBidDto.java
  pickme/src/main/java/project/pickme/bid/dto/reqeust/AddBidDto.java
  pickme/src/main/java/project/pickme/bid/dto/reqeust/ExitMemberDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/BidCreateDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/BidResult.java
  pickme/src/main/java/project/pickme/bid/dto/response/MaxPriceDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/OneBidItemDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/SelectedBidDto.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketHandShakeInterceptor.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketHandler.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketService.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketSessionRepository.java
  pickme/src/main/java/project/pickme/common/auth/CustomsDetailServiceImpl.java
  pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
  pickme/src/main/java/project/pickme/common/exception/ControllerAdvice.java
  pickme/src/main/java/project/pickme/common/exception/ErrorCode.java
  pickme/src/main/java/project/pickme/item/domain/Item.java
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/java/project/pickme/user/controller/UserRestController.java
  pickme/src/main/java/project/pickme/user/repository/CustomsMapper.java
  pickme/src/main/java/project/pickme/user/service/CustomsService.java
  pickme/src/main/java/project/pickme/user/service/MailService.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/static/css/bid/bidPage.css
  pickme/src/main/resources/static/css/charge/style.css
  pickme/src/main/resources/static/css/user/signUp.css
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/main/resources/static/js/bid/chart.js
  pickme/src/main/resources/static/js/bid/confetti.js
  pickme/src/main/resources/static/js/bid/timer.js
  pickme/src/main/resources/static/js/item/countdown.js
  pickme/src/main/resources/static/js/item/filtering.js
  pickme/src/main/resources/static/js/item/image.js
  pickme/src/main/resources/static/js/item/like.js
  pickme/src/main/resources/static/js/user/checkId.js
  pickme/src/main/resources/static/js/user/signUp.js
  pickme/src/main/resources/templates/bid/ErrorModal.html
  pickme/src/main/resources/templates/bid/bidPage.html
  pickme/src/main/resources/templates/charge/charge.html
  pickme/src/main/resources/templates/index.html
  pickme/src/main/resources/templates/item/item.html
  pickme/src/main/resources/templates/user/bidMail.html
  pickme/src/main/resources/templates/user/signUpForm.html
  pickme/src/test/java/project/pickme/bid/repository/BidMapperTest.java
Labels: FEAT, BE, REFACTOR, FE, STYLE

#59 [FEAT]: 낙찰자 포인트 결제 내역 저장
  pickme/src/main/java/project/pickme/bid/dto/response/BidResultDto.java
  pickme/src/main/java/project/pickme/bid/exception/BidErrorCode.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketHandler.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketService.java
  pickme/src/main/java/project/pickme/common/auth/CustomsDetailServiceImpl.java
  pickme/src/main/java/project/pickme/common/auth/UserDetailServiceImpl.java
  pickme/src/main/java/project/pickme/common/exception/ControllerAdvice.java
  pickme/src/main/java/project/pickme/common/exception/ErrorCode.java
  pickme/src/main/java/project/pickme/item/exception/ItemErrorCode.java
  pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
  pickme/src/main/java/project/pickme/payment/dto/SavePaymentDto.java
  pickme/src/main/java/project/pickme/payment/repository/PaymentMapper.java
  pickme/src/main/java/project/pickme/s3/service/S3Service.java
  pickme/src/main/java/project/pickme/user/domain/Customs.java
  pickme/src/main/java/project/pickme/user/exception/UserErrorCode.java
  pickme/src/main/java/project/pickme/user/repository/CustomsMapper.java
  pickme/src/main/java/project/pickme/user/service/CustomsService.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/mapper/CustomsMapper.xml
  pickme/src/main/resources/mapper/ItemMapper.xml
  pickme/src/main/resources/mapper/PaymentMapper.xml
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/test/java/project/pickme/bid/repository/BidMapperTest.java
  pickme/src/test/java/project/pickme/item/repository/ItemMapperTest.java
  pickme/src/test/java/project/pickme/payment/repository/PaymentMapperTest.java
  pickme/src/test/java/project/pickme/user/controller/UserRestControllerTest.java
  pickme/src/test/java/project/pickme/user/service/UserServiceTest.java
Labels: FEAT, BE, REFACTOR, TEST

#63 [FEAT]: itemservice에서 s3부분 삭제
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
  pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
  pickme/src/main/java/project/pickme/item/service/ItemService.java
  pickme/src/main/resources/static/css/item/item.css
  pickme/src/main/resources/static/js/item/item.js
  pickme/src/main/resources/templates/item/createItem.html
Labels: FIX, FEAT, BE, REFACTOR, FE, STYLE

#65 [REFACTOR]: 에러코드부분 수정
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
  pickme/src/main/java/project/pickme/item/exception/ItemErrorCode.java
  pickme/src/main/java/project/pickme/s3/service/S3Service.java
  pickme/src/main/resources/application-s3.yml
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/mapper/CustomsMapper.xml
  pickme/src/main/resources/templates/item/createItem.html
Labels: BE, REFACTOR

#77 [FEAT]: 아이템 리스트 화면에서 좋아요 버튼 구현
  pickme/src/main/java/project/pickme/item/FindItemService.java
  pickme/src/main/java/project/pickme/item/controller/FindItemController.java
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/css/item/style.css
  pickme/src/main/resources/static/js/item/like.js
  pickme/src/main/resources/templates/item/item.html
  pickme/src/main/resources/templates/item/list.html
Labels: BE, FE

#69 [FEAT]: 입찰 관련 추가 구현 + 리팩토링
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
  pickme/src/main/java/project/pickme/bid/dto/reqeust/SelectedBidDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/BidCreateDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/BidDetailsDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/BidDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/MaxPriceDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/OneBidItemDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/PriceDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/UpdatePriceBidDto.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/java/project/pickme/bid/service/MailService.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketHandler.java
  pickme/src/main/java/project/pickme/bid/webSocket/WebSocketService.java
  pickme/src/main/java/project/pickme/common/auth/CustomAuthenticationSuccessHandler.java
  pickme/src/main/java/project/pickme/common/response/BaseResponse.java
  pickme/src/main/java/project/pickme/image/dto/ImageDto.java
  pickme/src/main/java/project/pickme/image/repository/ImageMapper.java
  pickme/src/main/java/project/pickme/item/controller/FindItemController.java
  pickme/src/main/java/project/pickme/item/dto/OneBidItemDto.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
  pickme/src/main/java/project/pickme/item/service/FindItemService.java
  pickme/src/main/java/project/pickme/s3/service/S3Service.java
  pickme/src/main/java/project/pickme/user/controller/UserRestController.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/mapper/ImageMapper.xml
  pickme/src/main/resources/mapper/ItemMapper.xml
  pickme/src/main/resources/static/css/bid/bidPage.css
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/main/resources/static/js/bid/chart.js
  pickme/src/main/resources/static/js/bid/modal.js
  pickme/src/main/resources/static/js/bid/price.js
  pickme/src/main/resources/templates/bid/bidPage.html
  pickme/src/main/resources/templates/bid/modal.html
  pickme/src/test/java/project/pickme/bid/repository/BidMapperTest.java
  pickme/src/test/java/project/pickme/item/repository/FindItemMapperTest.java
  pickme/src/test/java/project/pickme/payment/repository/PaymentMapperTest.java
Labels: FEAT, BE, REFACTOR, FE, TEST

#80 [FEAT]: 아이템 페이지 연결
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/images/default_img.png
  pickme/src/main/resources/static/js/item/request.js
  pickme/src/main/resources/templates/item/item.html
  pickme/src/main/resources/templates/item/list.html
Labels: FEAT, REFACTOR, FE

#81 [FEAT]: myPage 사이드 바 화면 구현
  pickme/src/main/java/project/pickme/common/auth/CustomAuthenticationSuccessHandler.java
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/resources/static/css/user/myPage.css
  pickme/src/main/resources/static/images/like.png
  pickme/src/main/resources/static/images/myInfo.png
  pickme/src/main/resources/static/images/payment.png
  pickme/src/main/resources/static/js/user/myPage.js
  pickme/src/main/resources/templates/user/myPage.html
Labels: FEAT, FE

#83 [STYLE]: 포인트 충전 화면 css 구현
  pickme/src/main/resources/static/css/charge/charge.css
  pickme/src/main/resources/static/css/user/myPage.css
  pickme/src/main/resources/static/js/charge/charge.js
  pickme/src/main/resources/templates/charge/charge.html
Labels: FE, STYLE

#92 [FEAT]: 아이템 조회 화면에서 입찰 화면으로 연결
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/js/item/countdown.js
  pickme/src/main/resources/templates/item/item.html
Labels: FIX, FEAT, FE

#97 [FEAT]: 메인페이지 전용 헤더 구현
  pickme/src/main/resources/static/css/common/userMainHeader.css
  pickme/src/main/resources/templates/userMainHeader.html
Labels: FEAT, FE

#86 [FEAT]: Customs 메인 및 헤더 구현
  pickme/src/main/java/project/pickme/user/controller/CustomsController.java
  pickme/src/main/resources/static/css/customs/customsHeader.css
  pickme/src/main/resources/static/css/customs/customsMain.css
  pickme/src/main/resources/static/images/campaign.png
  pickme/src/main/resources/static/images/delivery-courier.png
  pickme/src/main/resources/templates/customs/customsHeader.html
  pickme/src/main/resources/templates/customs/customsMain.html
Labels: FEAT, FE

#104 [FIX]: 오류 나는 부분 수정, 헤더, 사이드 바 페이지 연결
  pickme/src/main/java/project/pickme/bid/dto/response/BidDetailsDto.java
  pickme/src/main/java/project/pickme/bid/service/MailService.java
  pickme/src/main/java/project/pickme/common/auth/CustomAuthenticationSuccessHandler.java
  pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
  pickme/src/main/java/project/pickme/user/controller/CustomsController.java
  pickme/src/main/java/project/pickme/user/controller/MainController.java
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/main/resources/static/js/bid/chart.js
  pickme/src/main/resources/templates/bid/bidPage.html
  pickme/src/main/resources/templates/fragments/header.html
  pickme/src/main/resources/templates/fragments/userMainHeader.html
  pickme/src/main/resources/templates/index.html
  pickme/src/main/resources/templates/user/bidMail.html
  pickme/src/main/resources/templates/user/userInfoEditForm.html
Labels: FIX, BE, REFACTOR

#106 [FEAT]: 아이템 상세조회 화면 css 구현
  pickme/src/main/resources/static/css/item/detail.css
  pickme/src/main/resources/static/images/department.png
  pickme/src/main/resources/static/images/phone.png
  pickme/src/main/resources/static/images/won.png
  pickme/src/main/resources/templates/item/item.html
Labels: FEAT, FE, STYLE

#107 [STYLE]: 통화 적용, 시간대에 T삭제, 글씨 컬러적용등 전체적인 css수정
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/bid/dto/MySuccessfulBidDto.java
  pickme/src/main/java/project/pickme/bid/dto/SuccessfulBidDto.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/java/project/pickme/delivery/controller/DeliveryController.java
  pickme/src/main/java/project/pickme/delivery/controller/DeliveryRestController.java
  pickme/src/main/java/project/pickme/delivery/dto/DeliveryFormDto.java
  pickme/src/main/java/project/pickme/delivery/dto/DeliveryManageDto.java
  pickme/src/main/java/project/pickme/delivery/repository/DeliveryMapper.java
  pickme/src/main/java/project/pickme/delivery/service/DeliveryService.java
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
  pickme/src/main/java/project/pickme/item/dto/ItemDto.java
  pickme/src/main/java/project/pickme/item/dto/SuccessfullCustomsItemDto.java
  pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
  pickme/src/main/java/project/pickme/item/service/ItemService.java
  pickme/src/main/resources/application-delivery.yml
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/mapper/DeliveryMapper.xml
  pickme/src/main/resources/mapper/ItemMapper.xml
  pickme/src/main/resources/static/css/bid/success.css
  pickme/src/main/resources/static/css/delivery/register.css
  pickme/src/main/resources/static/js/delivery/register.js
  pickme/src/main/resources/static/js/item/item.js
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
  pickme/src/main/resources/templates/bid/successfulBidList.html
  pickme/src/main/resources/templates/customs/customsHeader.html
  pickme/src/main/resources/templates/customs/customsMain.html
  pickme/src/main/resources/templates/delivery/delivery.html
  pickme/src/main/resources/templates/delivery/register.html
  pickme/src/main/resources/templates/delivery/status.html
  pickme/src/main/resources/templates/item/createItem.html
  pickme/src/main/resources/templates/item/customsItems.html
  pickme/src/main/resources/templates/item/updateItem.html
Labels: FIX, BE, FE, STYLE

#108 [FIX]: 화면 연결 문제 수정 및 화면 요소 크기 수정
  pickme/src/main/resources/static/css/item/detail.css
  pickme/src/main/resources/static/js/item/countdown.js
  pickme/src/main/resources/templates/item/item.html
Labels: FE

#110 [STYLE]: 배송 관리 페이지 헤더 적용
  pickme/src/main/resources/templates/delivery/delivery.html
Labels: FE, STYLE

#113 [FEAT]: 아이템 상태 변경 기능 구현
  pickme/src/main/java/project/pickme/PickmeApplication.java
  pickme/src/main/java/project/pickme/item/repository/ItemMapper.java
  pickme/src/main/java/project/pickme/item/service/ItemSchedulingService.java
  pickme/src/main/resources/mapper/ItemMapper.xml
Labels: FEAT, BE

#115 [FEAT]: 아이템 리스트 정렬조건 추가
  pickme/src/main/resources/mapper/FindItemMapper.xml
Labels: FEAT, BE

#71 [FEAT]: Customs 사이드바 구현
  pickme/src/main/resources/static/css/customs/customsSidebar.css
  pickme/src/main/resources/static/js/customs/customsSidebar.js
  pickme/src/main/resources/templates/customs/customsSidebar.html
Labels: FEAT, FE

#118 [STYLE]: 메인 글씨 로고 축소 및 상품 가격단위 콤마 추가
  pickme/src/main/resources/static/css/common/userMainHeader.css
  pickme/src/main/resources/templates/index.html
Labels: FE, STYLE

#121 [FEAT]: 내 포인트 사용 목록
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/charge/repository/ChargeMapper.java
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/java/project/pickme/user/dto/PointHistoryDto.java
  pickme/src/main/java/project/pickme/user/repository/UserMapper.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/mapper/ChargeMapper.xml
  pickme/src/main/resources/mapper/UserMapper.xml
  pickme/src/main/resources/static/css/common/footer.css
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/css/user/infoEdit.css
  pickme/src/main/resources/static/css/user/pointHistory.css
  pickme/src/main/resources/static/images/chargeCoin.png
  pickme/src/main/resources/static/images/paymentCoin.png
  pickme/src/main/resources/static/js/user/pointHistory.js
  pickme/src/main/resources/static/js/userMain.js
  pickme/src/main/resources/templates/bid/bidPage.html
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
  pickme/src/main/resources/templates/customs/customsHeader.html
  pickme/src/main/resources/templates/fragments/myPageSidebar.html
  pickme/src/main/resources/templates/user/pointHistory.html
  pickme/src/main/resources/templates/user/userInfoEditForm.html
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FEAT, BE, FE, TEST

#124 [FEAT]: 카테고리 필터링 기능 추가
  pickme/src/main/java/project/pickme/item/controller/FindItemController.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/java/project/pickme/item/service/FindItemService.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/templates/item/list.html
Labels: FEAT, BE, FE

#133 [FEAT]: 공매품 작성 페이지 화면 구현
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
  pickme/src/main/java/project/pickme/item/dto/ItemFormDto.java
  pickme/src/main/java/project/pickme/user/controller/MainController.java
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/resources/static/css/bid/bidPage.css
  pickme/src/main/resources/static/css/customs/customsSidebar.css
  pickme/src/main/resources/static/css/item/item.css
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/js/item/item.js
  pickme/src/main/resources/templates/bid/bidPage.html
  pickme/src/main/resources/templates/customs/customsSidebar.html
  pickme/src/main/resources/templates/item/createItem.html
  pickme/src/main/resources/templates/item/customsItems.html
  pickme/src/main/resources/templates/layouts/layout.html
Labels: FEAT, REFACTOR, FE, STYLE

#137 [FEAT]: 아이템 조회시 호가표 추가
  pickme/src/main/java/project/pickme/unit/domain/Unit.java
  pickme/src/main/resources/static/css/item/detail.css
  pickme/src/main/resources/static/js/item/unit.js
  pickme/src/main/resources/templates/item/item.html
Labels: FEAT, FE

#140 [FEAT]: 메인 페이지 접속 상태 구분 및 공매품 상위 20개 나열 구현
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/java/project/pickme/item/service/FindItemService.java
  pickme/src/main/java/project/pickme/user/controller/MainController.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/templates/fragments/userMainHeader.html
Labels: FEAT, FE

#141 [FEAT]: 아이템 조회시 관련 법규 조회 기능 추가
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/java/project/pickme/item/dto/LawDto.java
  pickme/src/main/java/project/pickme/item/repository/LawMapper.java
  pickme/src/main/java/project/pickme/item/service/FindItemService.java
  pickme/src/main/resources/mapper/LawMapper.xml
  pickme/src/main/resources/static/css/item/detail.css
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/images/all.png
  pickme/src/main/resources/static/js/item/filtering.js
  pickme/src/main/resources/static/js/item/law.js
  pickme/src/main/resources/templates/item/item.html
  pickme/src/main/resources/templates/item/list.html
Labels: FEAT, BE, FE

#146 [FEAT]: 배송관리 페이지 사이드바 적용
  pickme/src/main/resources/templates/delivery/delivery.html
Labels: STYLE

#135 [FEAT]: 포인트 사용 내역 페이징 처리
  pickme/build.gradle
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/java/project/pickme/user/controller/UserRestController.java
  pickme/src/main/java/project/pickme/user/repository/UserMapper.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/mapper/UserMapper.xml
  pickme/src/main/resources/static/css/user/pointHistory.css
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/main/resources/static/js/user/pointHistory.js
  pickme/src/main/resources/templates/fragments/myPageSidebar.html
  pickme/src/main/resources/templates/user/pointHistory.html
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FEAT, BE, REFACTOR, FE

#125 [FEAT]: 송장 등록 및 배송 조회 구현
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/delivery/controller/CustomsDeliveryController.java
  pickme/src/main/java/project/pickme/delivery/controller/UserDeliveryController.java
  pickme/src/main/java/project/pickme/delivery/dto/DeliveryFormDto.java
  pickme/src/main/java/project/pickme/delivery/dto/DeliveryInfoDto.java
  pickme/src/main/java/project/pickme/delivery/dto/ItemInfoDto.java
  pickme/src/main/java/project/pickme/delivery/repository/DeliveryMapper.java
  pickme/src/main/java/project/pickme/delivery/service/DeliveryService.java
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
  pickme/src/main/java/project/pickme/user/constant/Type.java
  pickme/src/main/resources/mapper/DeliveryMapper.xml
  pickme/src/main/resources/static/css/delivery/register.css
  pickme/src/main/resources/static/css/delivery/status.css
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
  pickme/src/main/resources/templates/delivery/delivery.html
  pickme/src/main/resources/templates/delivery/register.html
  pickme/src/main/resources/templates/delivery/status.html
Labels: BE, REFACTOR, FE, STYLE

#149 [REFACTOR]: 없어진 코드 복구
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/templates/item/list.html
Labels: BE, REFACTOR, FE

#154 [STYLE]: 아이템 리스트 css 수정
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/images/all.png
  pickme/src/main/resources/static/js/item/like.js
Labels: FIX, FE, STYLE

#155 [STYLE]: 포인트 충전 화면 디자인 수정
  pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
  pickme/src/main/resources/static/css/charge/charge.css
  pickme/src/main/resources/templates/charge/charge.html
Labels: FE, STYLE

#147 [FEAT]: 로그아웃 기능 구현
  pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
  pickme/src/main/resources/templates/customs/customsHeader.html
  pickme/src/main/resources/templates/fragments/header.html
  pickme/src/main/resources/templates/index.html
Labels: FEAT, BE

#158 [STYLE]: 아이템 상세조회 css 수정
  pickme/src/main/resources/static/css/item/detail.css
  pickme/src/main/resources/templates/item/item.html
Labels: FE, STYLE

#160 [STYLE]: User/Customs 헤더 디자인 통일
  pickme/src/main/resources/static/css/common/footer.css
  pickme/src/main/resources/static/css/common/header.css
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/css/user/infoEdit.css
  pickme/src/main/resources/templates/fragments/footer.html
  pickme/src/main/resources/templates/fragments/header.html
  pickme/src/main/resources/templates/item/list.html
Labels: FE, STYLE

#162 [FEAT]: 오류 페이지 구현
  pickme/src/main/java/project/pickme/common/exception/GlobalControllerAdvice.java
  pickme/src/main/java/project/pickme/common/exception/GlobalRestControllerAdvice.java
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/static/css/error/404.css
  pickme/src/main/resources/static/css/error/500.css
  pickme/src/main/resources/static/images/404.svg
  pickme/src/main/resources/static/images/500.svg
  pickme/src/main/resources/templates/error/404.html
  pickme/src/main/resources/templates/error/500.html
Labels: FEAT, BE, FE

#167 [FEAT]: 관심 목록 조회 기능 구현
  pickme/src/main/java/project/pickme/item/controller/FindItemController.java
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/java/project/pickme/item/service/FindItemService.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/css/item/wishList.css
  pickme/src/main/resources/static/js/item/request.js
  pickme/src/main/resources/static/js/item/wishList.js
  pickme/src/main/resources/templates/fragments/myPageSidebar.html
  pickme/src/main/resources/templates/item/wishList.html
Labels: FEAT, BE, FE

#165 [FEAT]: 수입관리 기능 구현
  pickme/src/main/java/project/pickme/user/controller/CustomsController.java
  pickme/src/main/java/project/pickme/user/controller/CustomsRestController.java
  pickme/src/main/java/project/pickme/user/controller/UserRestController.java
  pickme/src/main/java/project/pickme/user/dto/customs/IncomeDto.java
  pickme/src/main/java/project/pickme/user/dto/user/PointHistoryDto.java
  pickme/src/main/java/project/pickme/user/dto/user/UpdateInfoDto.java
  pickme/src/main/java/project/pickme/user/dto/user/UpdatePasswordDto.java
  pickme/src/main/java/project/pickme/user/repository/CustomsMapper.java
  pickme/src/main/java/project/pickme/user/repository/UserMapper.java
  pickme/src/main/java/project/pickme/user/service/CustomsService.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/mapper/CustomsMapper.xml
  pickme/src/main/resources/mapper/UserMapper.xml
  pickme/src/main/resources/static/css/common/pagination.css
  pickme/src/main/resources/static/css/customs/income.css
  pickme/src/main/resources/static/css/user/pointHistory.css
  pickme/src/main/resources/static/js/common/pagination.js
  pickme/src/main/resources/static/js/customs/income.js
  pickme/src/main/resources/static/js/user/pointHistory.js
  pickme/src/main/resources/templates/customs/customsHeader.html
  pickme/src/main/resources/templates/customs/incomeForm.html
  pickme/src/main/resources/templates/user/pointHistory.html
  pickme/src/test/java/project/pickme/user/controller/UserRestControllerTest.java
  pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FEAT, BE, REFACTOR, FE, TEST, STYLE

#170 [HOTFIX]: CustomsService 주석처리
  pickme/src/main/java/project/pickme/user/service/CustomsService.java
Labels: FIX, BE

#171 [FIX]: 테스트 오류 수정
  pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java
Labels: FIX

#173 [CHORE]: yml 파일 수정
  pickme/src/main/resources/application.yml
Labels: BE

#168 [STYLE]: 메인 헤더 및 각종 디자인 개선
  pickme/src/main/resources/static/css/common/header.css
  pickme/src/main/resources/static/css/customs/customsHeader.css
  pickme/src/main/resources/templates/customs/customsHeader.html
  pickme/src/main/resources/templates/fragments/header.html
Labels: FEAT, FE, STYLE

#129 [FEAT]: 관리자 공지 및 캠페인 관리 페이지
  pickme/src/main/java/project/pickme/notice/constant/NoticeType.java
  pickme/src/main/java/project/pickme/notice/controller/CampaignController.java
  pickme/src/main/java/project/pickme/notice/controller/CampaignRestController.java
  pickme/src/main/java/project/pickme/notice/controller/NoticeController.java
  pickme/src/main/java/project/pickme/notice/controller/NoticeRestController.java
  pickme/src/main/java/project/pickme/notice/converter/CampaignConverter.java
  pickme/src/main/java/project/pickme/notice/converter/NoticeConverter.java
  pickme/src/main/java/project/pickme/notice/domain/Notice.java
  pickme/src/main/java/project/pickme/notice/dto/CampaignDto.java
  pickme/src/main/java/project/pickme/notice/dto/NoticeDto.java
  pickme/src/main/java/project/pickme/notice/repository/NoticeMapper.java
  pickme/src/main/java/project/pickme/notice/service/CampaignService.java
  pickme/src/main/java/project/pickme/notice/service/NoticeService.java
  pickme/src/main/java/project/pickme/s3/service/S3Service.java
  pickme/src/main/resources/mapper/NoticeMapper.xml
  pickme/src/main/resources/static/css/common/footer.css
  pickme/src/main/resources/static/css/notice/campaignContent.css
  pickme/src/main/resources/static/css/notice/campaignForm.css
  pickme/src/main/resources/static/css/notice/campaignList.css
  pickme/src/main/resources/static/css/notice/noticeContent.css
  pickme/src/main/resources/static/css/notice/noticeForm.css
  pickme/src/main/resources/static/css/notice/noticeList.css
  pickme/src/main/resources/static/images/camera.png
  pickme/src/main/resources/static/images/warning.png
  pickme/src/main/resources/static/js/notice/campaignContent.js
  pickme/src/main/resources/static/js/notice/campaignForm.js
  pickme/src/main/resources/static/js/notice/campaignList.js
  pickme/src/main/resources/static/js/notice/noticeContent.js
  pickme/src/main/resources/static/js/notice/noticeForm.js
  pickme/src/main/resources/static/js/notice/noticeList.js
  pickme/src/main/resources/templates/notice/campaignContent.html
  pickme/src/main/resources/templates/notice/campaignForm.html
  pickme/src/main/resources/templates/notice/campaignList.html
  pickme/src/main/resources/templates/notice/noticeContent.html
  pickme/src/main/resources/templates/notice/noticeForm.html
  pickme/src/main/resources/templates/notice/noticeList.html
Labels: FEAT, BE, FE

#73 [FEAT]: 통계 대시보드 페이지 구현
  pickme/src/main/resources/static/css/statistics/statisticsDashboard.css
  pickme/src/main/resources/templates/statistics/statisticsDashboard.html
Labels: FEAT, FE

#174 [FIX]: 스프링 시큐리티 동시 로그인 차단 안되는 문제 해결
  pickme/src/main/java/project/pickme/common/auth/CustomsDetailsImpl.java
  pickme/src/main/java/project/pickme/common/auth/UserDetailsImpl.java
  pickme/src/main/java/project/pickme/common/config/WebSecurityConfig.java
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/main/resources/templates/customs/customsHeader.html
  pickme/src/main/resources/templates/fragments/header.html
  pickme/src/test/java/project/pickme/bid/repository/BidMapperTest.java
  pickme/src/test/java/project/pickme/item/repository/FindItemMapperTest.java
  pickme/src/test/java/project/pickme/payment/repository/PaymentMapperTest.java
  pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FIX, BE, REFACTOR

#179 [FEAT]: 메인 페이지 캠페인 페이지네이션
  pickme/src/main/java/project/pickme/notice/repository/NoticeMapper.java
  pickme/src/main/java/project/pickme/notice/service/CampaignService.java
  pickme/src/main/java/project/pickme/user/controller/MainController.java
  pickme/src/main/resources/mapper/NoticeMapper.xml
  pickme/src/main/resources/static/css/userMain.css
  pickme/src/main/resources/static/js/userMain.js
  pickme/src/main/resources/templates/index.html
Labels: FEAT, BE, FE

#186 [FEAT]: 아이템 리스트 조회 비동기 처리 및 페이지네이션 구현
  pickme/src/main/java/project/pickme/item/controller/FindUserItemController.java
  pickme/src/main/java/project/pickme/item/controller/FindUserItemRestController.java
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/java/project/pickme/item/dto/ItemRequest.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/java/project/pickme/item/service/FindItemService.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/css/item/list.css
  pickme/src/main/resources/static/js/item/filtering.js
  pickme/src/main/resources/static/js/item/infiniteScroll.js
  pickme/src/main/resources/static/js/item/itemNavigation.js
  pickme/src/main/resources/static/js/item/like.js
  pickme/src/main/resources/static/js/item/likeHandler.js
  pickme/src/main/resources/static/js/item/list.js
  pickme/src/main/resources/static/js/item/request.js
  pickme/src/main/resources/templates/item/list.html
Labels: FIX, FEAT, BE, FE

#180 [FEAT]: 내 결제 목록 페이지네이션 적용
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/java/project/pickme/payment/repository/PaymentMapper.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/mapper/PaymentMapper.xml
  pickme/src/main/resources/static/js/bid/successfulBidList.js
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
  pickme/src/main/resources/templates/fragments/myPageSidebar.html
Labels: FEAT, BE, REFACTOR, FE

#182 [FEAT]: 관심 상품 목록 페이징 처리
  pickme/src/main/java/project/pickme/item/controller/FindUserItemController.java
  pickme/src/main/java/project/pickme/item/controller/FindUserItemRestController.java
  pickme/src/main/java/project/pickme/item/repository/FindItemMapper.java
  pickme/src/main/java/project/pickme/item/service/FindItemService.java
  pickme/src/main/java/project/pickme/user/service/CustomsService.java
  pickme/src/main/resources/mapper/CustomsMapper.xml
  pickme/src/main/resources/mapper/DeliveryMapper.xml
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/css/item/wishList.css
  pickme/src/main/resources/static/js/item/wishList.js
  pickme/src/main/resources/templates/item/wishList.html
Labels: FEAT, BE, REFACTOR, STYLE

#183 [FEAT]: 유저들이 보는 공지사항 페이지
  pickme/src/main/java/project/pickme/notice/controller/UserNoticeController.java
  pickme/src/main/java/project/pickme/notice/controller/UserNoticeRestController.java
  pickme/src/main/java/project/pickme/notice/repository/NoticeMapper.java
  pickme/src/main/java/project/pickme/notice/service/NoticeService.java
  pickme/src/main/resources/mapper/NoticeMapper.xml
  pickme/src/main/resources/static/css/notice/userNoticeContent.css
  pickme/src/main/resources/static/css/notice/userNoticeList.css
  pickme/src/main/resources/static/js/notice/userNoticeList.js
  pickme/src/main/resources/templates/fragments/header.html
  pickme/src/main/resources/templates/notice/userNoticeContent.html
  pickme/src/main/resources/templates/notice/userNoticeList.html
Labels: FEAT, BE, FE

#191 [FIX]: 좋아요 오류 수정
  pickme/src/main/java/project/pickme/item/dto/FindItemDto.java
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/static/js/item/wishList.js
  pickme/src/main/resources/templates/item/item.html
  pickme/src/main/resources/templates/item/wishList.html
Labels: FIX, BE, FE

#187 [REFACTOR]: 리뷰 반영하여 리팩토링
  pickme/src/main/java/project/pickme/delivery/controller/CustomsDeliveryController.java
  pickme/src/main/java/project/pickme/image/repository/ImageMapper.java
  pickme/src/main/java/project/pickme/item/controller/ItemRestController.java
  pickme/src/main/java/project/pickme/item/dto/UpdateDto.java
  pickme/src/main/java/project/pickme/item/dto/UpdateItemFormDto.java
  pickme/src/main/java/project/pickme/item/service/ItemService.java
  pickme/src/main/java/project/pickme/s3/service/S3Service.java
  pickme/src/main/resources/mapper/ImageMapper.xml
  pickme/src/main/resources/static/css/delivery/delivery.css
  pickme/src/main/resources/static/css/delivery/status.css
  pickme/src/main/resources/static/css/delivery/userStatus.css
  pickme/src/main/resources/static/js/delivery/delivery.js
  pickme/src/main/resources/static/js/delivery/status.js
  pickme/src/main/resources/static/js/item/createItem.js
  pickme/src/main/resources/static/js/item/edit.js
  pickme/src/main/resources/static/js/item/item.js
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
  pickme/src/main/resources/templates/delivery/delivery.html
  pickme/src/main/resources/templates/delivery/register.html
  pickme/src/main/resources/templates/delivery/status.html
  pickme/src/main/resources/templates/delivery/userStatus.html
  pickme/src/main/resources/templates/item/createItem.html
  pickme/src/main/resources/templates/item/editItem.html
  pickme/src/test/java/project/pickme/item/repository/FindItemMapperTest.java
  pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java
Labels: FEAT, BE, FE, TEST, STYLE

#188 [FEAT]: Customs 메인페이지 공지 및 캠페인 연결
  pickme/src/main/java/project/pickme/notice/controller/CustomsMainRestController.java
  pickme/src/main/java/project/pickme/notice/repository/NoticeMapper.java
  pickme/src/main/java/project/pickme/notice/service/CampaignService.java
  pickme/src/main/java/project/pickme/notice/service/CustomsMainService.java
  pickme/src/main/java/project/pickme/user/controller/MainController.java
  pickme/src/main/resources/mapper/NoticeMapper.xml
  pickme/src/main/resources/static/css/customs/customsMain.css
  pickme/src/main/resources/static/js/customs/customsMain.js
  pickme/src/main/resources/templates/customs/customsMain.html
Labels: FEAT, BE, FE

#200 [STYLE]: 법규 모달창 사이즈 조절
  pickme/src/main/resources/static/css/item/detail.css
  pickme/src/main/resources/templates/item/item.html
Labels: FE, STYLE

#198 [FEAT]: 낙찰 처리 스케줄러 구현
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
  pickme/src/main/java/project/pickme/bid/dto/reqeust/SelectedBidDto.java
  pickme/src/main/java/project/pickme/bid/dto/response/UnPaidBidDto.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/java/project/pickme/bid/service/MailService.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/static/css/bid/success.css
  pickme/src/main/resources/static/css/bid/unpaidBid.css
  pickme/src/main/resources/static/images/credit-card-payment.png
  pickme/src/main/resources/static/js/bid/bid.js
  pickme/src/main/resources/static/js/bid/unpaidBid.js
  pickme/src/main/resources/templates/bid/unpaidBidList.html
  pickme/src/main/resources/templates/fragments/myPageSidebar.html
  pickme/src/test/java/project/pickme/bid/controller/BidRestControllerTest.java
Labels: FEAT, BE, FE

#208 [FIX]: 마이페이지 유저 포인트 업데이트 오류 수정
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/item/controller/FindUserItemController.java
  pickme/src/main/java/project/pickme/user/controller/MainController.java
  pickme/src/main/java/project/pickme/user/controller/UserController.java
  pickme/src/main/java/project/pickme/user/service/UserService.java
  pickme/src/main/resources/templates/fragments/myPageSidebar.html
Labels: FIX, BE

#210 [CHORE]: mybatis logging 설정
  pickme/src/main/java/project/pickme/item/controller/FindUserItemRestController.java
  pickme/src/main/resources/application.yml
  pickme/src/main/resources/mapper/ItemMapper.xml
  pickme/src/main/resources/static/css/item/detail.css
  pickme/src/main/resources/templates/item/item.html
Labels: BE

#206 [FEAT]: 결제 기능 구현
  pickme/src/main/java/project/pickme/bid/dto/response/UnPaidBidDto.java
  pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
  pickme/src/main/java/project/pickme/payment/controller/PaymentRestController.java
  pickme/src/main/java/project/pickme/payment/dto/PaymentDto.java
  pickme/src/main/java/project/pickme/payment/dto/SavePaymentDto.java
  pickme/src/main/java/project/pickme/payment/exception/PaymentErrorCode.java
  pickme/src/main/java/project/pickme/payment/repository/PaymentMapper.java
  pickme/src/main/java/project/pickme/payment/service/PaymentService.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/mapper/PaymentMapper.xml
  pickme/src/main/resources/static/css/bid/unpaidBid.css
  pickme/src/main/resources/static/js/bid/unpaidBid.js
  pickme/src/main/resources/templates/bid/unpaidBidList.html
  pickme/src/test/java/project/pickme/payment/repository/PaymentMapperTest.java
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FEAT, BE, FE

#212 [STYLE]: 전체적으로 아이콘 이미지 변경
  pickme/src/main/resources/static/images/analytics.png
  pickme/src/main/resources/static/images/auction.png
  pickme/src/main/resources/static/images/campaign.png
  pickme/src/main/resources/static/images/credit-card.png
  pickme/src/main/resources/static/images/data-analysis.png
  pickme/src/main/resources/static/images/delivery-courier.png
  pickme/src/main/resources/static/images/express-delivery.png
  pickme/src/main/resources/static/images/heart.png
  pickme/src/main/resources/static/images/like.png
  pickme/src/main/resources/static/images/myInfo.png
  pickme/src/main/resources/static/images/myPage.png
  pickme/src/main/resources/static/images/p.png
  pickme/src/main/resources/static/images/paper.png
  pickme/src/main/resources/static/images/payment.png
  pickme/src/main/resources/static/images/point.png
  pickme/src/main/resources/static/images/search-engine.png
  pickme/src/main/resources/static/images/search.png
  pickme/src/main/resources/static/images/test.jpg
  pickme/src/main/resources/static/images/web-profile.png
  pickme/src/main/resources/templates/customs/customsMain.html
  pickme/src/main/resources/templates/fragments/myPageSidebar.html
  pickme/src/main/resources/templates/index.html
Labels: FE, STYLE

#203 [FEAT]: 경매 관련 통계 페이지 구현
  pickme/src/main/java/project/pickme/statistics/controller/StatisticsController.java
  pickme/src/main/java/project/pickme/statistics/controller/StatisticsRestController.java
  pickme/src/main/java/project/pickme/statistics/dto/CategoryCompetitionDto.java
  pickme/src/main/java/project/pickme/statistics/dto/MonthlyBidStatisticsDto.java
  pickme/src/main/java/project/pickme/statistics/repository/StatisticsMapper.java
  pickme/src/main/java/project/pickme/statistics/service/StatisticsService.java
  pickme/src/main/resources/mapper/StatisticsMapper.xml
  pickme/src/main/resources/static/css/statistics/auction.css
  pickme/src/main/resources/static/js/statistics/auction.js
  pickme/src/main/resources/templates/statistics/auction.html
Labels: FEAT, BE, FE

#213 [STYLE]: 각종 디자인 개선
  pickme/src/main/resources/static/css/common/footer.css
  pickme/src/main/resources/static/css/notice/campaignContent.css
  pickme/src/main/resources/static/css/notice/noticeContent.css
  pickme/src/main/resources/static/css/user/infoEdit.css
  pickme/src/main/resources/static/css/userMain.css
  pickme/src/main/resources/static/js/userMain.js
  pickme/src/main/resources/templates/customs/customsMain.html
  pickme/src/main/resources/templates/fragments/footer.html
  pickme/src/main/resources/templates/item/item.html
  pickme/src/main/resources/templates/notice/campaignContent.html
  pickme/src/main/resources/templates/notice/noticeContent.html
Labels: FE, STYLE

#202 [REFACTOR]: 리뷰 반영하여 리팩토링
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/mapper/DeliveryMapper.xml
  pickme/src/main/resources/static/css/delivery/delivery.css
  pickme/src/main/resources/static/js/delivery/delivery.js
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
Labels: REFACTOR

#218 [FEAT]: image bulk insert 오류 수정
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/image/repository/ImageMapper.java
  pickme/src/main/resources/mapper/ImageMapper.xml
Labels: REFACTOR

#219 [FEAT]: 낙찰 관련 오류 수정
  pickme/src/main/java/project/pickme/bid/controller/BidController.java
  pickme/src/main/java/project/pickme/bid/repository/BidMapper.java
  pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
  pickme/src/main/java/project/pickme/delivery/repository/DeliveryMapper.java
  pickme/src/main/java/project/pickme/user/service/CustomsService.java
  pickme/src/main/resources/mapper/BidMapper.xml
  pickme/src/main/resources/mapper/DeliveryMapper.xml
  pickme/src/main/resources/mapper/FindItemMapper.xml
  pickme/src/main/resources/mapper/ImageMapper.xml
  pickme/src/main/resources/mapper/ItemLawMapper.xml
  pickme/src/main/resources/mapper/ItemMapper.xml
  pickme/src/main/resources/mapper/NoticeMapper.xml
  pickme/src/main/resources/mapper/StatisticsMapper.xml
  pickme/src/main/resources/mapper/UserMapper.xml
  pickme/src/main/resources/static/css/bid/success.css
  pickme/src/main/resources/static/js/bid/successfulBidList.js
  pickme/src/main/resources/static/js/bid/unpaidBid.js
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
  pickme/src/main/resources/templates/bid/unpaidBidList.html
  pickme/src/main/resources/templates/index.html
  pickme/src/test/java/project/pickme/bid/controller/BidRestControllerTest.java
  pickme/src/test/java/project/pickme/item/repository/FindItemMapperTest.java
  pickme/src/test/java/project/pickme/user/repository/UserMapperTest.java
Labels: FIX, FEAT, REFACTOR, STYLE

#222 [REFACTOR]: 주소에 슬래시 제거
  pickme/src/main/java/project/pickme/delivery/controller/CustomsDeliveryController.java
  pickme/src/main/java/project/pickme/delivery/controller/UserDeliveryController.java
  pickme/src/main/java/project/pickme/item/controller/ItemController.java
Labels: BE, REFACTOR

#221 [REFACTOR]: 수입 조회 쿼리 결제 내역 조건 추가
  pickme/src/main/resources/mapper/CustomsMapper.xml
Labels: REFACTOR

#226 [REFACTOR]: 테이블 너비 변경
  pickme/src/main/resources/static/css/bid/success.css
  pickme/src/main/resources/static/css/delivery/status.css
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
  pickme/src/main/resources/templates/delivery/userStatus.html
Labels: FE, STYLE

#227 [STYLE]: 메인 화면 아이템 hover 효과 추가
  pickme/src/main/resources/static/css/userMain.css
Labels: FE, STYLE

#224 [REFACTOR]: 수입이 없는 경우 기본 포인트 0으로 설정
  pickme/src/main/resources/static/js/customs/income.js
  pickme/src/main/resources/static/js/user/myPage.js
Labels: REFACTOR

#229 [FIX]: 수익 확인 테스트 코드 오류 수정
  pickme/src/test/java/project/pickme/user/repository/CustomsMapperTest.java
Labels: FIX, TEST

#232 [FIX]: 결제 후 다시 화면 load 하도록 수정
  pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
  pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
  pickme/src/main/java/project/pickme/bid/service/BidService.java
  pickme/src/main/resources/static/js/bid/unpaidBid.js
Labels: FIX

#233 [REFACTOR]: 세관쪽 content 위치 조정
  pickme/src/main/resources/static/css/item/item.css
Labels: STYLE

#234 [FEAT]: 통계페이지 구현 및 디자인 개선
  pickme/src/main/java/project/pickme/bid/service/BidSchedulingService.java
  pickme/src/main/java/project/pickme/item/service/ItemSchedulingService.java
  pickme/src/main/resources/mapper/StatisticsMapper.xml
  pickme/src/main/resources/templates/customs/customsSidebar.html
  pickme/src/main/resources/templates/index.html
Labels: FIX, FE, STYLE

#235 [STYLE]: 대시보드 배경 페이지 변경
  pickme/src/main/resources/static/css/statistics/dashboard.css
Labels: FE, STYLE

#236 [STYLE]: 버튼 색 변경 및 기타 통계 coming soon 제거
  pickme/src/main/resources/static/css/common/myPageSidebar.css
  pickme/src/main/resources/static/js/statistics/etc.js
  pickme/src/main/resources/templates/statistics/etc.html
Labels: FE, STYLE

#239 [FIX]: "/user/bidMail" url / 제거
  pickme/src/main/java/project/pickme/bid/service/MailService.java
Labels: FIX
