Repository SYSONE-PICKME/PICKME, pull requests merged in 2024-10, with the labels that each got.

#243 [STYLE]: 내 결제 목록 사이드 바 위치 하단 고정
  pickme/src/main/resources/static/css/bid/success.css
  pickme/src/main/resources/templates/bid/bidPage.html
  pickme/src/main/resources/templates/bid/mySuccessfulBidList.html
Labels: STYLE

#241 [DOCS]: javaDoc추가
  pickme/src/main/java/project/pickme/bid/controller/BidRestController.java
  pickme/src/main/java/project/pickme/delivery/constant/DeliveryType.java
  pickme/src/main/java/project/pickme/delivery/controller/DeliveryRestController.java
  pickme/src/main/java/project/pickme/delivery/doamin/Delivery.java
  pickme/src/main/java/project/pickme/item/controller/ItemRestController.java
  pickme/src/main/resources/static/css/delivery/userStatus.css
Labels: DOCS

#245 [FIX]: 시간 오류 수정
  pickme/src/main/resources/templates/bid/bidPage.html
Labels: FIX
